# Question1:
##  Q.1 - Create a numpy array with 10 elements of the shape(10,1) using np.random and find out the mean of the elements using basic numpy functions.


In [13]:
import numpy as np
a=np.random.rand(10,1)
print(a)
print(a.mean())


[[0.33833021]
 [0.21346132]
 [0.72827381]
 [0.24356487]
 [0.74632123]
 [0.30000323]
 [0.28733002]
 [0.6212264 ]
 [0.28690176]
 [0.74083786]]
0.4506250710759597


# Question2:
## Q.2 - Create a numpy array with 20 elements of the shape(20,1) using np.random find the variance and standard deviation of the elements.

In [14]:
import numpy as np
a=np.random.rand(20,1)
print(a)
print(a.std())
print(a.var())

[[0.67540756]
 [0.99873973]
 [0.11900304]
 [0.27789061]
 [0.66742809]
 [0.06683651]
 [0.84417376]
 [0.4374546 ]
 [0.73901187]
 [0.39815285]
 [0.30935187]
 [0.79071349]
 [0.37892411]
 [0.44307218]
 [0.03903775]
 [0.11622496]
 [0.85941432]
 [0.57238092]
 [0.45389637]
 [0.49180599]]
0.27472864896899096
0.07547583056432706


# Question3:
## Q.3 - Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25). Using basic numpy math functions only find the sum of all the elements of the new matrix.

In [20]:
import numpy as np
a=np.random.rand(10,20)
b=np.random.rand(20,25)
c=np.matmul(a,b)
print(c)
print(c.sum())


[[5.13189473 5.19793069 4.97360738 4.87992393 4.57407795 3.65030143
  4.86271328 6.13355159 5.89059284 5.2363731  5.41723521 6.21975876
  4.89944112 5.74974359 5.64507383 4.72415477 5.02712019 5.34798667
  3.99685828 5.32202981 4.0426046  5.39977696 3.81977398 4.63743996
  5.4524091 ]
 [3.40363908 3.72875003 3.42503443 4.25249366 2.93637608 2.87380655
  4.09887334 3.99294867 4.48631262 3.93602566 4.2219766  5.0009357
  4.51040063 4.58003708 3.93975553 4.09525812 4.35830395 4.65685694
  3.63076112 3.98338676 3.67605762 3.91955938 3.3401647  3.4289611
  3.85793995]
 [5.93577547 5.88729308 5.37672359 5.76534643 4.90527791 3.89845204
  5.38294437 6.81563348 6.68968913 5.35309477 6.18300075 6.29387779
  6.01312289 6.09883084 6.27807383 5.84108446 5.65346498 6.38146447
  4.89374215 6.46351274 4.8576902  6.17964638 4.01192528 5.45043773
  6.20321925]
 [5.31498136 4.72221666 5.04514207 5.84951715 4.3757726  4.01830442
  5.98074186 6.40846527 6.30816806 6.40022745 6.2267201  6.28451926
  5.9213

# Question4:
## Q.4 - Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) such that each element is the following function applied on each element of A. 


In [33]:

import numpy as np
a=np.random.rand(10,1)
print(a)
def func(x) :
    return (1/(1+np.exp (-x)))
result=np.apply_along_axis(func , 0 , a)
print(result)

[[0.44883283]
 [0.23574692]
 [0.33939633]
 [0.18678856]
 [0.07106701]
 [0.44433599]
 [0.90250827]
 [0.80165108]
 [0.94713112]
 [0.63376519]]
[[0.61036169]
 [0.55866528]
 [0.58404388]
 [0.54656184]
 [0.51775928]
 [0.60929172]
 [0.71146468]
 [0.69032755]
 [0.72053786]
 [0.65334272]]
